# Configuración global
per_listener_settings true

# ----------------------------------------------------
# Listener 1: TCP (Para mosquitto_pub/sub y sensores físicos)
# ----------------------------------------------------
listener 1883
protocol mqtt
allow_anonymous true

# ----------------------------------------------------
# Listener 2: WebSockets (Para tu Frontend React)
# ----------------------------------------------------
listener 9001
protocol websockets
allow_anonymous true